### ISSUE TITLE
Pigs randomly dissapearing?

### ISSUE THREAD

**Issue by GeorgeOrwell1** [joshiejack/Husbandry#1]
I'm not sure if this is a bug, but it seems like pigs in my pen after a while just randomly disappear (not dropping anything, just disappearing), and thought that maybe this mod is responsible for that?

Log: https://pastebin.com/4v4kB96

**Comment by joshiejack** [comment]
It's possible, ya never know though. But to be able to do anything I'd need something reproducible/concrete evidence. I know someone has tested this out and played with their animals for at least 112 minecraft days without this happening. The only time this mod kills an entity is when it is considered "old" and even then it would drop things since I don't kill it. Just do a ton of damage to it.

**Comment by GeorgeOrwell1** [comment]
Well I don't know what else to do other than to let you know lol. It's not like I can prove it as it happens randomly after maybe a Minecraft day or two.
